layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-php
  - jekyll-github-metadata
  - jemoji

permalink: /:path/
include: [.php]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

other_display_info:
  email: 
    display: vf@ign.ku.dk
  
  employment: 
    display: University of Copenhagen
    url: https://researchprofiles.ku.dk/en/persons/valentina-s-espinoza-fern%C3%A1ndez


social_media:
  researchgate: Valentina-Espinoza-2

topics:
  - name: Ergonomic Keyboards
    web_url: https://github.com/ValeEspinozaF/UFO_splitkb
    image_url: https://github.com/ValeEspinozaF/personal-website/blob/master/assets/images/UFO_keyboard.PNG?raw=true

  - name: Blender Scripting
    description: Python scrips for 3D modelling
    web_url: https://github.com/ValeEspinozaF/Blender_scripts
    image_url: https://raw.githubusercontent.com/ValeEspinozaF/personal-website/refs/heads/master/assets/images/Blender_python_scripts.PNG

  - name: Easing Animations
    description: Python class for dynamic data visualizations
    web_url: https://github.com/ValeEspinozaF/Easing-Animations-with-Python/tree/master
    image_url: https://raw.githubusercontent.com/ValeEspinozaF/Easing-Animations-with-Python/refs/heads/master/examples/media/overshoot_ease.gif
